spring:
  application:
    name: customer-service
  #mongodb:
    #uri: mongodb://root:example@mongo:27017/customerdb
  #data:
    #mongodb:
      #uri: mongodb://127.0.0.1:27017/customerdb

server:
  port: 8000

customer-service:
  mongo-server-url: mongodb://customerdbuser:password@127.0.0.1:27017/admin
  db-name: customerdb
  collection-name: customer

#logging:
  #level:
   # org:
      #springframework: debug