version: '3.9'

services:
  customer-service:
    image: brij2804/mongodb-customer-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - project_network
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - project_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - project_network
    volumes:
      - mongodb:/data/db
      
#networks:
  #project_network:
    #external: true

networks:
  project_network:

volumes:
   mongodb:
    external: true   