version: '3.9'

services:

  #customer-service:
    #image: brij2804/mongodb-customer-service:0.0.1-SNAPSHOT
    #mem_limit: 700m
    #ports:
      #- "8000:8000"
    #networks:
      #- project_network
    #depends_on:
      #- mongo
    #environment:
      #MONGODB_URI: mongodb://mongo:27017

  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    hostname: mongodb
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
      #MONGODB_ROOT_PASSWORD: password
      #authenticationDatabase: admin
      #MONGO_INITDB_DATABASE: admin
      #MONGODB_DATABASE: customerdb
      #MONGODB_USER: customerdbuser
      #MONGODB_PASS: password
    command:
      - --bind_ip_all
      #- --authenticationDatabase admin
    networks:
      - project_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

networks:
  project_network:
    #ipam:
      #config:
        #- subnet: 192.168.65.0/28

volumes:
   mongodb:
    external: true   
      