version: '3.9'

services:

  pricing-service:
    image: brij2804/mongodb-pricing-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8300:8300"
    networks:
      - project_network
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.5
    hostname: mongodbsvr
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command:
      - --bind_ip_all
    networks:
      - project_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

networks:
  project_network:

volumes:
   mongodb:
    external: true   