version: '3.9'

services:  
  mongo:
    image: mongo:4.4.5
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - project_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/var/lib/mongodb

  mongo-express:
    image: mongo-express:0.54.0
    hostname: mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - project_network
    volumes:
      - mongodb:/var/lib/mongodb    
      
networks:
  default:
    external:
      name: project_network

volumes:
   mongodb:
    external: true   